name: Deploy SAM EDA Application

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy (dev or prod)'
        required: true
        default: 'dev'

env:
  AWS_REGION: us-east-1
  SAM_TEMPLATE: template.yml

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ github.event_name == 'push' && 'dev' || github.event.inputs.environment }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Install SAM CLI
        run: pip install aws-sam-cli

      - name: SAM Validate
        run: sam validate --template ${{ env.SAM_TEMPLATE }}

      - name: SAM Build
        run: sam build --template ${{ env.SAM_TEMPLATE }}

      - name: SAM Deploy
        run: |
          sam deploy \
            --template-file ${{ env.SAM_TEMPLATE }} \
            --stack-name "eda-stack-${{ github.event_name == 'push' && 'dev' || github.event.inputs.environment }}" \
            --region ${{ env.AWS_REGION }} \
            --capabilities CAPABILITY_IAM \
            --no-confirm-changeset \
            --no-fail-on-empty-changeset \
            --parameter-overrides \
              Environment=${{ github.event_name == 'push' && 'dev' || github.event.inputs.environment }} \
              EmailAddresses=${{ secrets.EMAIL_ADDRESSES }}
