name: Deploy SAM EDA Application

on:
  push:
    branches:
      - main
      - test

env:
  AWS_REGION: us-east-1
  DEV_EMAILS: ${{ secrets.DEV_EMAILS }}
  PROD_EMAILS: ${{ secrets.PROD_EMAILS }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install

      - name: Build TypeScript Project
        run: npm run build

      - name: Setup AWS SAM CLI
        uses: aws-actions/setup-sam@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Validate Emails
        run: |
          BRANCH_NAME="${GITHUB_REF##*/}"
          if [[ "$BRANCH_NAME" == "main" ]]; then
            EMAILS="${{ secrets.PROD_EMAILS }}"
          elif [[ "$BRANCH_NAME" == "test" ]]; then
            EMAILS="${{ secrets.DEV_EMAILS }}"
          fi
          if [[ ! "$EMAILS" =~ ^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}(,[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,})*$ ]]; then
            echo "Invalid email format in ${BRANCH_NAME} email secret"
            exit 1
          fi

      - name: Build SAM Application
        run: sam build --template sam/template.yml

      - name: Deploy SAM Application
        run: |
          BRANCH_NAME="${GITHUB_REF##*/}"
          if [[ "$BRANCH_NAME" == "main" ]]; then
            sam deploy --config-env prod --parameter-overrides "EmailAddresses=${PROD_EMAILS}"
          elif [[ "$BRANCH_NAME" == "test" ]]; then
            sam deploy --config-env dev --parameter-overrides "EmailAddresses=${DEV_EMAILS}"
          else
            echo "Branch not configured for deployment: $BRANCH_NAME"
          fi
